services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: pagila-postgres-prisma-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pagila-test
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - '5433:5432'
